runtime: python313

default_expiration: "3650d"

manual_scaling:
  instances: 1
  
handlers:
- url: /
  static_files: pages/@tmd-build/pages/index.html
  upload: pages/index.html
  expiration: "1d"

- url: /@assets/(.*)
  static_files: pages/@tmd-build/pages/@assets/\1
  upload: pages/@assets/(.*)

- url: /(.*)
  static_files: pages/@tmd-build/pages/\1
  upload: pages/(.*)
  expiration: "1d"

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
