runtime: python39

default_expiration: "3650d"

manual_scaling:
  instances: 1
  
handlers:
- url: /
  static_files: pages/@tmd-build/pages/index.html
  upload: pages/index.html
  expiration: "1d"

- url: /images/(.*)
  static_files: pages/@tmd-build/pages/images/\1
  upload: pages/images/(.*)

- url: /css/(.*)
  static_files: pages/@tmd-build/pages/css/\1
  upload: pages/images/(.*)

- url: /js/(.*)
  static_files: pages/@tmd-build/pages/js/\1
  upload: pages/images/(.*)

- url: /(.*)
  static_files: pages/@tmd-build/pages/\1
  upload: pages/(.*)
  expiration: "1d"

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
